/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheKeySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAmountSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheOffsetSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheItemsSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCategoriesSchema = TheItemsSchema[];
/**
 * An explanation about the purpose of this instance.
 */
export type TheItemsSchema1 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIngredientsSchema = TheItemsSchema1[];

/**
 * The root schema comprises the entire JSON document.
 */
export interface GetDataQuery {
  key?: TheKeySchema;
  amount: TheAmountSchema;
  offset: TheOffsetSchema;
  categories?: TheCategoriesSchema;
  ingredients?: TheIngredientsSchema;
}
